### ISSUE TITLE
Can we have an instant (in-page) translation option?

### ISSUE THREAD

**Issue by lealceldeiro** [itsecurityco/to-google-translate#100]
When a text is selected in a page, to translate it we have two options:

1 - Right click > "To Google Translate" > "Translate" (this will open a new tab for the google translate page)
2 - Copy + paste text into *Google Translate* add-on (after clicking in it)

I would LOVE to have an option of an "instant" translate option. My idea is that once a text is selected, automatically *To Google Translate* shows an option to translate the text without needing to navigate to the google translate page or without needing to open the add-on in the add-ons bar on the browser.

As a reference this feature is implemented here: https://chrome.google.com/webstore/detail/translate-selected-text/fbimffnjoeobhjhochngikepgfejjmgj

For that there is a configuration as shown in the following image

![Screenshot from 2020-05-12 09-23-02](https://user-images.githubusercontent.com/15990580/81645528-66ab4f00-9432-11ea-8f82-e9abdcfabf92.png)

![Screenshot from 2020-05-12 09-26-58](https://user-images.githubusercontent.com/15990580/81645790-dae5f280-9432-11ea-9a8b-983026119928.png)

**Comment by itsecurityco** [comment]
Hello @lealceldeiro, 

Have you tried the Open in Modal configuration in the option page? 

Let me know

**Comment by lealceldeiro** [comment]
@itsecurityco , Thanks for the quick reply. Definitely I overlooked that option. I just checked it and it fits my needs :)

So, feel free to close the issue, or in case you plan to implement it the way I described it, just leave it open, I'll leave it to your consideration.
