### ISSUE TITLE
Popup window does not load

### ISSUE THREAD

**Issue by JuliaSzulc** [itsecurityco/to-google-translate#119]
As in the title. It's just a black window with loading animation. It occurs both when selecting text and launching the addon from the context menu and when clicking the button in the toolbar. The same issue was pointed out in the addon review [here](https://addons.mozilla.org/en-US/firefox/addon/to-google-translate/reviews/1616283/?utm_content=addons-manager-reviews-link&utm_medium=firefox-browser&utm_source=firefox-browser).

Firefox 82.0.2

![Screenshot_2020-10-30 Classwork for ht20-sfi KS72 Beata Studium](https://user-images.githubusercontent.com/26124131/97716310-befb0980-1ac3-11eb-8b73-cfe4476657ee.png)

**Comment by olivit** [comment]
The same for me.
If I set the option "modal" (default) it doesn't work anymore, however it keeps working by setting the option "New Tab"
Thanks sm and keep the good work!
(MS Windows 10 Pro, Firefox v.82.0.2)

**Comment by Patyrsa** [comment]
I have the same problem, thanks for "new tab" decision

**Comment by mitcrepe** [comment]
I have the same problem. On one PC it doens't work , and on my other PC the extension works, with the same Firefox version.

**Comment by ahmedkk96** [comment]
Same problem here, I updated Firefox 2 days ago to 82.0.2 and I think that's what broke it.
Also the popup still doesn't work when using the "new tab" option instead of "modal".

**Comment by Dezeter** [comment]
Yap! Same problem

**Comment by Zorrototo** [comment]
Firefox 82.0.2 (64 bits) on Linux Manjaro KDE

Same issue when I select text, right click, and select `translate (auto/fr)` the popup opens, I see google translate website load for a split second and then it goes to a dark background with nothing in the popup.

**Comment by GSnuki** [comment]
Same problem...
Firefox 82.0.2 (64 bits) on Win 7 x64

**Comment by guptautkarsh64** [comment]
I have Windows 7 Ultimate SP1 x64 Firefox 80.0.2 
Same problem

**Comment by varesssz** [comment]
I have the same issue with it
Firefox 82.0.2 (64 bit) Win10

**Comment by Juraj-Masiar** [comment]
It seems that Google is applying some new "security" protection to some users/requests and redirects iframe to "about:blank".
This looks bad.

**Comment by tinakuzmenko** [comment]
I have the same problem. Firefox Developer Edition 83.0b8 (64 bit) MacOS Catalina.
When I ckick on the plugin button to open pop-up it blinks from the normal interface to the loader. And that's all.

**Comment by fuatkarakus** [comment]
I have the same problem with Firefox Developer Edition 83.0b8 (64-bit).

**Comment by libroc** [comment]
Same issues... Workaround: 
- To translate a page: Right click on an empty space in a webpage and go to "Translate this page (auto/yxz)".
- To translate words or sentences: Mark it, right click it and go "To Google Translate > Translate (auto/yxz?)". If it doesn't work (sometimes does it tho), click on the "+" sign top right (and a new tab will open).

**Comment by JuliaSzulc** [comment]
> 
> 
> Same issues...
> 
> Workaround:
> 
>     * **To translate a page**: Right click on an empty space in a webpage and go to "Translate this page (auto/yxz)".
> 
>     * **To translate words/sentences/paragraphs**: Mark it, right click it, go "To Google Translate > Translate (auto/yxz)", click on the "+" sign top right and a new tab will open (sometimes it will work though).

Well,

**Comment by JuliaSzulc** [comment]
> 
> 
> Same issues...
> 
> Workaround:
> 
> * **To translate a page**: Right click on an empty space in a webpage and go to "Translate this page (auto/yxz)".
> * **To translate words/sentences/paragraphs**: Mark it, right click it, go "To Google Translate > Translate (auto/yxz)", click on the "+" sign top right and a new tab will open (sometimes it will work though).

Well, my workaround was to install a similar addon that works fine

**Comment by bam80** [comment]
@JuliaSzulc which is that?

**Comment by itsecurityco** [comment]
Hello, thank you for the report. I have uploaded an update that disabled modal feature to fix this issue. The new version is 4.1.0 and it's in the queue for been approved by the Firefox team. In the mean time you can change the option "Open in" from "Modal" to "New Tab" in the Options page.

**Comment by fabiorfreitas** [comment]
That's not at all a solution, it doesn't solve the problem, but avoids it. Losing this feature could be enough to switch to another addon.

**Comment by guptautkarsh64** [comment]
> 
> 
> That's not at all a solution, it doesn't solve the problem, but avoids it. Losing this feature could be enough to switch to another addon.

She is right we chose this addon because of its accessibility features. If we need to open another window why not open google itself.

**Comment by bam80** [comment]
Is the another concurrent addon exists?
