### ISSUE TITLE
Broken toolbar popup window 

### ISSUE THREAD

**Issue by H-F-T** [itsecurityco/to-google-translate#120]
This issue occurred recently when I added 1 more google account to my browser. The toolbar page flashes when it loads up and goes black. It only works in incognito mode because there it's not logged in into any google accounts. I tried running google translate add-on alone by uninstalling all others.

[https://i.imgur.com/gIWd1Ap.png](https://i.imgur.com/gIWd1Ap.png)

**Comment by itsecurityco** [comment]
Hello, thank you for the report. I have uploaded an update that disabled this feature. The new version 4.1.0 will work with tabs like the previous versions of extension and it's in the queue for been approved by the Firefox team.
