### ISSUE TITLE
Apparently the extension itself has translation errors

### ISSUE THREAD

**Issue by ialima** [itsecurityco/to-google-translate#126]
Many bugs. The extension name does not appear in the settings and context menu. It looks like a (oddly) translation error. It is displaying codes and their descriptions where the texts should be displayed. The place of the extension name has just become: "extensionName Nome da extensão"
![image](https://user-images.githubusercontent.com/13965192/110147918-f99ae880-7dba-11eb-8eca-433a4e94401f.png)
![image](https://user-images.githubusercontent.com/13965192/110148240-59918f00-7dbb-11eb-9d6f-0ccea82e65dd.png)

**Comment by ialima** [comment]
After posting I saw that I can try to suggest fix to the localization file myself (I know what Github is for, but I'm not very familiar with its use). I did (https://github.com/itsecurityco/to-google-translate/commit/4c7170f4ed23c226f599fd4d92a0cb4728144ef8). I hope you appreciate my contribution. Now expect to accept and update the extension.

**Comment by felipeaf** [comment]
same here. I can't understand why this commit wasn't accepted yet. This bug turns the extension unusable for Brazilian users.

**Comment by itsecurityco** [comment]
Hello, thank you for the PR, I'm reviewing right now.

Cheers!

**Comment by ialima** [comment]
Thanks!

**Comment by itsecurityco** [comment]
Merged, the problem was that a crowdin.com user made some updates in locales but he did the translate into the description too, not only values :/

The update will be available soon once Mozilla team approves the new version.

**Comment by itsecurityco** [comment]
Fix is already available in the last version of add-on. @ialima
