### ISSUE TITLE
Google domain names in China need special changes.

### ISSUE THREAD

**Issue by NorthNanmu** [itsecurityco/to-google-translate#18]
Hi! Here is a Chinese user's request.
For some unspeakable reasons, we do not normally use Google Translate under the https://translate.google.com domain in China, but the good news is that we can use https://translate.google.cn this domain, I really like this plugin, but it requires me to use proxies all the time to keep my plugin running.
Can you make some special adjustments for China area?
Sincerely thank you!

**Comment by itsecurityco** [comment]
I need find a way to detect throught JavaScript if the user is from China in order to change the domain to .cn. Can you check if this trick works?

```
var offset = new Date().getTimezoneOffset();
if(offset/60 == -8){
    console.log('Hello from China!');
}
```

Taken from: https://stackoverflow.com/questions/26645987/check-if-user-is-using-browser-located-in-china-or-not

**Comment by NorthNanmu** [comment]
Yes！ It works!
This is the screenshot I tested in Firefox and Chrome

![ihy0xhvi8r jj0p6gpalc 0](https://user-images.githubusercontent.com/28924440/36627129-4acf3f2a-1979-11e8-97ec-52cfebd12fea.png)

![ap iacd 22 p7 ha4v0qzpa](https://user-images.githubusercontent.com/28924440/36627131-4b44909a-1979-11e8-9c81-d085d64fe8a2.png)

**Comment by itsecurityco** [comment]
Google domain name in China has been added in the new version 3.1. I appreciate if you can go update and test it. Regards.
