### ISSUE TITLE
Cannot input "yue-Hant-HK" into "Text to Speech" box

### ISSUE THREAD

**Issue by s-ccy** [itsecurityco/to-google-translate#24]
Cantonese (Hong Kong spoken Chinese) is one of the supported text-to-speech languages by Google. Its language code is "yue-Hant-HK". However the "Text to Speech" box doesn't allow me to input "yue-Hant-HK" into the box in the settings.

**Comment by itsecurityco** [comment]
@s-ccy thank you for your report. I'm working on it.
Regards

**Comment by ituser8** [comment]
selecting them

**Comment by itsecurityco** [comment]
Looks like Cantonese has been disabled from Google Translate and TTS. https://productforums.google.com/forum/#!topic/translate/nS0VlgAdvJk

**Comment by s-ccy** [comment]
In the link, I don't see anywhere that says Cantonese has been disabled
from Google Translate and TTS. All I could see was someone called Calvin
asking for confirmation whether the support of Cantonese has been stopped.

As a web developer, I have been using Google's Cloud Text-to-Speech service
primarily for English, Chinese - Mandarin and Chinese - Cantonese
(yue-Hant-HK). Up to this day, it still functions alright with these
languages.

**Comment by itsecurityco** [comment]
I just release an update to the extension in the firefox website, now you can add the locate "yue-Hant-HK" to TTS in options page, but still the Google site don't recognize the locale.

https://translate.google.com/translate_tts?ie=UTF-8&total=1&idx=0&client=tw-ob&tl=yue-Hant-HK&q=Cantonese&textlen=9

![image](https://user-images.githubusercontent.com/1725054/41047784-4f67e1a2-697b-11e8-8479-6a8377d70a73.png)

![image](https://user-images.githubusercontent.com/1725054/41047736-3a68703c-697b-11e8-91e0-77030cc60c8c.png)

Also, I looked into the Google site to find a locale for Cantonese, but I can't saw it.

![image](https://user-images.githubusercontent.com/1725054/41047886-873d78da-697b-11e8-9599-d903d41821b6.png)

Maybe

**Comment by s-ccy** [comment]
I think you might have confused with the language options.
Chinese (Traditional) (HanT) is the written language.
Chinese (Cantonese) (yue, HK) is the spoken language.

I am not sure how the process works in your code, but I assume you have to
first translate the written text to Chinese (Traditional) and then pick
Chinese (Cantonese) to convert the text to speech.

yue-Hant-HK basically means Chinese with written as Traditional Chinese and
spoken as Chinese Cantonese.

**Comment by itsecurityco** [comment]
I think Cartonese can't be used with the TTS functionality in the addon. Because with the CORS protection I'm unable to read content from Google domain.
