### ISSUE TITLE
Can't Sign in to google.com

### ISSUE THREAD

**Issue by montaro** [itsecurityco/to-google-translate#29]
Firefox is already signed in to the google.com, however in the translation pop-up, I still see the *Sign in* button. When I click on that button, the page get redirected to https://translate.google.com/m/translate?pli=1 and I can see I'm already signed in.

Refreshing page didn't help as well as restarting the browser.
My FF version is `61.0.2 (64-bit)`
My add-on version is `3.3`

**Comment by itsecurityco** [comment]
Hello, OS are you using? A mobile one?

**Comment by hpsaturn** [comment]
Hi, In my Firefox (72.0.1 (64-bit)), I can't sign in because the pop up window, after sign in click, is too small and the flow of sign in is impossible, like this:

![translator_issue](https://user-images.githubusercontent.com/423856/72661410-018ea200-39da-11ea-9448-8ff4162a65c5.png)

**Comment by sKopheK** [comment]
Hi, I can sign in, however, it redirect the whole tab to the translate.google.com, where I was signed in before already anyway. When I open another translation popup, I'm still not signed in.

**Comment by ymkim92** [comment]
I have the same issue. On my windows machine, it works fine. But on my Linux machine, I see the attached image when I press ctrl+shift+1.
![gtrns](https://user-images.githubusercontent.com/3033436/94888841-a8aa5f80-04bd-11eb-8ef1-f3f0f492b0bc.png)
