### ISSUE TITLE
Wrong domain selection

### ISSUE THREAD

**Issue by mirochnik** [itsecurityco/to-google-translate#33]
I live in Singapore. I have the same timezone as China. I'm not a Chinese neither I speak Chinese. But add-on sends me to a Chinese interface version of Google.Translate.

Current automatic domain location is very simplistic. It shows Chinese Google interface to all the people in the timezone of China. This timezone includes many other countries like Russia, Mongolia, Singapore, Philippines, Malaysia, Australia. 

 Please make domain selection an option in settings instead of current auto-detection.

**Comment by itsecurityco** [comment]
Added in 3.6 release, it can take some hours to been aproved by Firefox.
