### ISSUE TITLE
Encoded spaces (%20) not properly decoded back to spaces anymore

### ISSUE THREAD

**Issue by robertnabbe** [itsecurityco/to-google-translate#34]
Started happening March 13th, 2019.

> Me quiero suscribir pero no veo el campo para el teléfono móvil y poder recibir el SMS que me pide  

becomes in google translate:  

> Me%20quiero%20suscribir%20pero%20no%20veo%20el%20campo%20para%20el%20tel%C3%A9fono%20m%C3%B3vil%20y%20poder%20recibir%20el%20SMS%20que%20me%20pide
  
Happening in FF 65.0.1, OSX 10.14.3.

**Comment by itsecurityco** [comment]
Thank you, I will update the URL to https://translate.google.com/?tab=TT#view=home&op=translate

**Comment by itsecurityco** [comment]
Changed already upload to Firefox, I'm just waiting they Approve it.

**Comment by robertnabbe** [comment]
Awesome, thanks for acting fast!
