### ISSUE TITLE
Bug occurs the set value is empty.

### ISSUE THREAD

**Issue by err931** [itsecurityco/to-google-translate#36]
![Clipboard01](https://user-images.githubusercontent.com/46459949/54341622-99668580-467d-11e9-995a-bd0ebb21bf4b.png)

**OMG...** :dizzy_face:
Add-on has been updated, but the bug was found.

The build from the `master` branch, this bug did not reproduce.

**Comment by laniakea64** [comment]
This is because the file "options.js" is missing from version 3.4 package on AMO.  Copying that file in from the git repo fixes this issue.

**Comment by err931** [comment]
Okay. :sunglasses:

I'm curious about #33. We plan to issue a PR soon.
Best regards,

**Comment by itsecurityco** [comment]
Hi, sorry guys, I uploaded the extension to Firefox without the options.js file. I'm waiting Firefox approve the new version.

**Comment by laniakea64** [comment]
> I'm waiting Firefox approve the new version.

It's available now, and this new version 3.6 doesn't have this issue.  Thanks! :smiley:
