### ISSUE TITLE
Sending does not work properly.

### ISSUE THREAD

**Issue by Tubelerczyk** [itsecurityco/to-google-translate#37]
I have a translation problem after sending to translator.
![image](https://user-images.githubusercontent.com/41324346/54345134-b7fb5b00-4642-11e9-829f-65789d08405c.jpg)

**Comment by Tubelerczyk** [comment]
Today it is working properly.

**Comment by itsecurityco** [comment]
Fixed in 3.6 release, it can take some hours to been aproved by Firefox.
