### ISSUE TITLE
Switch the default website

### ISSUE THREAD

**Issue by chaffman** [itsecurityco/to-google-translate#45]
Hello，How do I switch the default website to https://translate.google.cn instead of ...com?
Thank you.

**Comment by itsecurityco** [comment]
Hello @chaffman 

You can switch it here: about:addons

![image](https://user-images.githubusercontent.com/1725054/55083535-73c87b80-5082-11e9-8574-d68b623a9efe.png)

**Comment by chaffman** [comment]
OK Thanks, I have a problem with the display here before.
![图片](https://user-images.githubusercontent.com/13845212/55086077-c0dc3a00-50e2-11e9-8d1d-73c4ce76cd13.png)

**Comment by itsecurityco** [comment]
Still have the problem?

**Comment by chaffman** [comment]
After I restart my computer, it shows up correctly.
