### ISSUE TITLE
Can't save setting

### ISSUE THREAD

**Issue by Fyrsten** [itsecurityco/to-google-translate#51]
Can't save setting, wants to switch from German to Danish

![billede](https://user-images.githubusercontent.com/54403727/63515597-7fae5180-c4eb-11e9-8f0a-2fa64f82708a.png)

nothing happens when I press save

**Comment by itsecurityco** [comment]
Hello,

There is a red alert in Text to Speach field. Did you try to setting some
value for this field?

Cheers

**Comment by Fyrsten** [comment]
Thanks a lot, now it works :-)
