### ISSUE TITLE
Disable Translate Page of Google Translate China Mainland Ver.

### ISSUE THREAD

**Issue by wordlesswind** [itsecurityco/to-google-translate#52]
Google does not offer the Translate Page service in China Mainland.
It will jump to https://translate.google.com.hk, which is not directly accessible in China Mainland.

**Comment by itsecurityco** [comment]
Hello @wordlesswind 

May you provide more detail about the error you are getting?

Thank you

**Comment by wordlesswind** [comment]
Hi @itsecurityco 

Translate Page is disabled in Google Translate China Mainland Ver.

It will 302 to https://translate.google.com.hk if you try to translate a Page.
E.g. https://translate.google.cn/translate?sl=auto&tl=zh-CN&u=https%3A%2F%2Fgithub.com
→ https://translate.google.com.hk/translate?sl=auto&tl=zh-CN&u=https%3A%2F%2Fgithub.com

But https://translate.google.com.hk is blocked in China Mainland.
So I think that when users choose to use China Mainland Ver., Translate Page feature should be turned off and tell them why to do that.

**Comment by chr314** [comment]
i guess this is happening so people can't use google translate as proxy to bypass the `Great Firewall`

**Comment by itsecurityco** [comment]
> Hi @itsecurityco
> 
> Translate Page is disabled in Google Translate China Mainland Ver.
> 
> It will 302 to https://translate.google.com.hk if you try to translate a Page.
> E.g. https://translate.google.cn/translate?sl=auto&tl=zh-CN&u=https%3A%2F%2Fgithub.com
> → https://translate.google.com.hk/translate?sl=auto&tl=zh-CN&u=https%3A%2F%2Fgithub.com
> 
> But https://translate.google.com.hk is blocked in China Mainland.
> So I think that when users choose to use China Mainland Ver., Translate Page feature should be turned off and tell them why to do that.

I think is easier for user to not use this feature instead of disabling from the add-on. Maybe if the user find a way to bypass this blocking will not be cool he can't translate pages.

**Comment by itsecurityco** [comment]
Hi @wordlesswind, I'm closing the issue. 

Please feel free to comment or reopen if you have ideas. From I understand the TTS and translate text should still working. 

Also, I forgot mention that this was added because was a request from users: https://github.com/itsecurityco/to-google-translate/issues/18 https://github.com/itsecurityco/to-google-translate/issues/26

Cheers!
