### ISSUE TITLE
New permissions?

### ISSUE THREAD

**Issue by omgitsraven** [itsecurityco/to-google-translate#55]
Firefox is prompting me to confirm new permissions in the latest update, which seem a lot more broadly-reaching than previously:

![image](https://user-images.githubusercontent.com/8540042/65559137-70199280-df07-11e9-86c2-187bc4b5e302.png)

Is this intended, or has the plugin been compromised by a third party?

**Comment by itsecurityco** [comment]
Hello, you can see the thread here https://github.com/itsecurityco/to-google-translate/pull/46

**Comment by omgitsraven** [comment]
Ahh, makes sense, thanks!
