### ISSUE TITLE
Artifacts under firefox 69.1 MacOS

### ISSUE THREAD

**Issue by RickSaiz** [itsecurityco/to-google-translate#56]
![image](https://user-images.githubusercontent.com/377489/65627517-eb318600-dfa5-11e9-8da6-294f123b0fc8.png)

**Comment by gusbemacbe** [comment]
Not just on macOS, it also happens on Linux and on Windows. I have still this problem.

**Comment by itsecurityco** [comment]
Hello @RickSaiz 

Thank you, may you please provide me the Browser Locales that are you using?

Cheers!

**Comment by Arenlor** [comment]
@itsecurityco Came here to report about this. The popout button loads fine to me, but I do see __MSG_extensionName__ here using en-US however I'm on Nightly (71).

**Comment by itsecurityco** [comment]
> @itsecurityco Came here to report about this. The popout button loads fine to me, but I do see **MSG_extensionName** here using en-US however I'm on Nightly (71).

Thank you, I already write to developer of library and I'll check on my own this week.

Cheers!

**Comment by itsecurityco** [comment]
Hello, the update is already in the AMO and should be available as soon as Firefox folks approve it.

**Comment by gusbemacbe** [comment]
I am still worried, because I have read the news that Mozilla will ban all the translation extensions which contain remote code, @itsecurityco.

**Comment by gusbemacbe** [comment]
@itsecurityco ?

**Comment by itsecurityco** [comment]
> @itsecurityco ?



> I am still worried, because I have read the news that Mozilla will ban all the translation extensions which contain remote code, @itsecurityco.

Don't worries. This extension is recommended by Mozilla. You can read more about it here: https://support.mozilla.org/en-US/kb/recommended-extensions-program

![image](https://user-images.githubusercontent.com/1725054/68340067-8305b200-00c4-11ea-9370-ca88e9460c16.png)

**Comment by itsecurityco** [comment]
@RickSaiz @gusbemacbe @Arenlor  the new version is already approved, you can now update the extension :)
