### ISSUE TITLE
The keyboard shortcuts confict with Firefox's keyboard shortcuts

### ISSUE THREAD

**Issue by azumukupoe** [itsecurityco/to-google-translate#58]
Paste (as plain text) and Exit
https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly

**Comment by itsecurityco** [comment]
Hey @azumukupoe,
Thank you, I changed to Ctrl + Shift + B. According to link sent, this shortcut is not in use. This will be ready in the next update.
Cheers
