### ISSUE TITLE
Keyboard shortcut for translate selection

### ISSUE THREAD

**Issue by jscher2000** [itsecurityco/to-google-translate#6]
This request was posted by a user on the Mozilla Support forum:

https://support.mozilla.org/questions/1168973

It appears you can set the keyboard combination in the manifest; I don't know if there is a way to do it programmatically.

https://developer.mozilla.org/Add-ons/WebExtensions/manifest.json/commands

**Comment by itseco** [comment]
Thank you, I will start to work in the feature soon.

Regards

**Comment by itsecurityco** [comment]
It's already merged :D Changes will take some days until Mozilla approves the new version.

**Comment by kazerniel** [comment]
Is there a way to make these optional or custom? `Ctrl+Shift+V` is already commonly used to paste text without formatting.

**Comment by jscher2000** [comment]
> Is there a way to make these optional or custom?

On the Add-ons page, if you click the gear icon at the upper right of the extensions list, you can use the Manage Extension Shortcuts page to override Ctrl+Shift+V with something you prefer. I assigned Ctrl+Alt+T, although I'm sure I'll forget that any minute now.

**Comment by kazerniel** [comment]
Hmm I don't have an option like that on that dropdown list. Maybe because I'm using Waterfox 56.2.14.

**Comment by jscher2000** [comment]
> Hmm I don't have an option like that on that dropdown list. Maybe because I'm using Waterfox 56.2.14.

Yes, it was added in Firefox 66.

**Comment by kazerniel** [comment]
Thanks! I rolled back to version 3.10 for now, as that automatic shortcut is really interfering with my usual workflow.

**Comment by itsecurityco** [comment]
Hello, the current version 4.0.2 fixed this. The new commands are: 

```
Ctrl + Shift + 1
Ctrl +  Shift +2
Ctrl  + Shift + 3
```
