### ISSUE TITLE
About this plugin is not accessible in mainland China

### ISSUE THREAD

**Issue by p19971018** [itsecurityco/to-google-translate#61]
It can't be used in China because its address is the requested translate.google.com link. This link is blocked. You can only use the https://translate.google.cn/ link, static getGoogleTranslatorDomain() {
         Let offset = new Date().getTimezoneOffset();
         // Domain for China
         If (offset / 60 === -8) {
             Return "translate.google.cn";
             // Domain for rest of world
         } else {
             Return "translate.google.com";
         }
     } This method is flawed, accessing the link of com

**Comment by itsecurityco** [comment]
> It can't be used in China because its address is the requested translate.google.com link. This link is blocked. You can only use the https://translate.google.cn/ link, static getGoogleTranslatorDomain() {
>          Let offset = new Date().getTimezoneOffset();
>          // Domain for China
>          If (offset / 60 === -8) {
>              Return "translate.google.cn";
>              // Domain for rest of world
>          } else {
>              Return "translate.google.com";
>          }
>      } This method is flawed, accessing the link of com

Hello,

I tried in Firefox 69.0.1 in Windows 10 and works fine. Maybe you have to change options Open in and select New Tab.

![image](https://user-images.githubusercontent.com/1725054/66617821-09ee6a00-ebad-11e9-805a-3ed1437e02b2.png)

Let me know.

**Comment by p19971018** [comment]
> Hi,
> 
> Is there another domain that is not blocked at this time so we can replace it instead of translate.google.cn?
> 
> Cheers!

In this Internet, only China has GFW, which means that there is no problem of website blocking in other countries. It is recommended to use only two links: translate.google.com and translate.google.cn.

**Comment by itsecurityco** [comment]
> > Hi,
> > Is there another domain that is not blocked at this time so we can replace it instead of translate.google.cn?
> > Cheers!
> 
> In this Internet, only China has GFW, which means that there is no problem of website blocking in other countries. It is recommended to use only two links: translate.google.com and translate.google.cn.

Hello @p19971018, 

I'm closing the issue. Please feel free to comment or reopen if you have ideas. From I understand the TTS and translate text should still working right?

Ref. https://github.com/itsecurityco/to-google-translate/issues/52

Cheers!
