### ISSUE TITLE
Are keyboard shortcuts fixed?

### ISSUE THREAD

**Issue by MichalMichalak** [itsecurityco/to-google-translate#62]
Hello. I am using to-google-translate for some time now and I like it a lot. Recently though I've found out that it has shadowed CTRL+SHIFT+V which I use extensively with clipboard manager.

Is there any way to change keyboard shortcuts? To be honest I use the extension from time to time only and would like it the best without using keyboard at all.

**Comment by chr314** [comment]
it is already fixed, wait for the update

**Comment by itsecurityco** [comment]
Hello, the update is already in the AMO and should be available as soon as Firefox folks approve it.

**Comment by itsecurityco** [comment]
@MichalMichalak the new version is already approved, you can now update the extension :)

**Comment by MichalMichalak** [comment]
🙇 Thanks!
