### ISSUE TITLE
Pop-up window title is not replaced with the intended title in Firefox

### ISSUE THREAD

**Issue by fatihdgn** [itsecurityco/to-google-translate#65]
Hello. As the issue title says the pop-up window title stays the default "__MSG_extensionName__" in the Firefox browser. I suppose it's not intentional. I did have a little chance to take a look at the source code and in the "src/config.js" file at the line 81, the "getLanguages" method is trying to get the default languages from the Chrome Runtime API. I suppose it's causing the bug because chrome namespace is not available in the Firefox. 

Here is the locale information that I gathered from the console;
navigator.browserLanguage: undefined
navigator.language: en-US
navigator.userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0

I might be wrong, because I've not thoroughly inspected the code, but from what I can understand, this could be the cause.

Hope it helps.

**Comment by itsecurityco** [comment]
Hello, the update is already in the AMO and should be available as soon as Firefox folks approve it.

**Comment by itsecurityco** [comment]
@fatihdgn the new version is already approved, you can now update the extension :)
