### ISSUE TITLE
MSG_extensionName instead addon name

### ISSUE THREAD

**Issue by maxborowsky** [itsecurityco/to-google-translate#66]
Instead addon name is shown "__MSG_extensionName__". Windows 10 / Fedora 31, Firefox 70 (browser language - English (US), preferred language - English (US)), addon version 4.0.0.

![Screenshot from 2019-11-02 11-19-23](https://user-images.githubusercontent.com/20723033/68068141-19537400-fd63-11e9-9a64-efa4dab4b853.png)

**Comment by DjDiabolik** [comment]
Exactly.. i goes here to report also :)

**Comment by itsecurityco** [comment]
Hello, the update is already in the AMO and should be available as soon as Firefox folks approve it.

**Comment by itsecurityco** [comment]
@maxborowsky @DjDiabolik the new version is already approved, you can now update the extension :)
