### ISSUE TITLE
Translations are injected into every iframe in the webpage

### ISSUE THREAD

**Issue by erdemkose** [itsecurityco/to-google-translate#74]
`To Google Translate version: 4.0.2`
`Firefox version: 70.0 (64-bit)`

After I selected a piece of text and clicked `translate` in the context menu, `To Google Translate` popup appears in the center but as you can see in the attached screen capture, every other iframe also displays the same popup. 

Here's the link: https://www.computerbase.de/2019-11/u-bahn-berlin-lte-empfang-telekom-vodafone/

You can see the other iframes above and on the right side of the main popup.

<img width="1198" alt="to-google-translate-popup-in-iframes" src="https://user-images.githubusercontent.com/4168527/68665659-bc19a880-0542-11ea-96c4-4da0019a8bb1.png">

**Comment by itsecurityco** [comment]
Hello again @erdemkose ,

Thank you for this, I need to do some test in other websites to make sure changing all_frames to false in manifest don't break anything. I will post updates here. 

Cheers!
