### ISSUE TITLE
Stylus themes not working in the extension.

### ISSUE THREAD

**Issue by Vulgaris-Viridis** [itsecurityco/to-google-translate#88]
If i go to https://translate.google.com/ my custom css theme is applied properly, but when translating page with this extension, the custom theme just flashes in the popup window and reverts to the default (white) one. So the support is clearly there but something is blocking it.

**Comment by itsecurityco** [comment]
Hello,

The google translate website is opened into a popup that has own border colors. But maybe if you post some screenshots we can go into this?

Thanks

**Comment by Vulgaris-Viridis** [comment]
Hi There @itsecurityco, 

I'll preface this with saying that it really is not that big of a deal, it's just that i use dark themes everywhere and it would be nice if this worked, that's all.

This is the one i use for google translate:
![4](https://user-images.githubusercontent.com/17363930/72551334-f2eaa280-3894-11ea-9792-7dfee696d825.png)

=====================================================

Right, so lets take this YT page for example (it's already in English but for the sake of the argument..)  
![1](https://user-images.githubusercontent.com/17363930/72550947-224cdf80-3894-11ea-939f-3c09018b9859.png)

if i choose to translate text it opens in the blue-white (deafult skin) window. 
![2](https://user-images.githubusercontent.com/17363930/72550992-37297300-3894-11ea-8778-da47e9ebe639.png)

If i otherwise choose to translate the page it still opens in the default blue-white skinned window.
![3](https://user-images.githubusercontent.com/17363930/72551194-a56e3580-3894-11ea-9fab-da4e4a2ccca1.png)


but for the brief moment it flashes like this, before reverting to the default blue one. :
![Untitled](https://user-images.githubusercontent.com/17363930/72551048-51635100-3894-11ea-9c8b-7b15ad5ed3ff.png)


So the dark theme i'm using could clearly work here in the popup windows of your extension but something is blocking it. Like i said it's not a big deal, if it can be fixed -great! if not...that's alright.

**Comment by itsecurityco** [comment]
Hello,

The modal creates a popup which load Google Translate URL. The blue border of the modal it's custom CSS of the extension, you can find it here and maybe edit it and load the extension manually (just need to zip the repository): https://github.com/itsecurityco/to-google-translate/blob/master/src/content/modal.css.

Anyways, the content itself is just the original Google Translate URL, so the white background is not the css of the extension, it's the original Google Translate HTML/CSS. I think maybe the request it's not loading your custom CSS because the iframe.

Cheers.

**Comment by Vulgaris-Viridis** [comment]
Hi @itsecurityco 

Thanks, works like a charm!

![Screenshot_2020-01-18 Google Translate - Copy](https://user-images.githubusercontent.com/17363930/72655719-a7b8b880-3996-11ea-9753-b6097402e67a.jpg)


Much appreciated. Cheers!

**Comment by itsecurityco** [comment]
Your welcome :)
