### ISSUE TITLE
Google Translator with Right Click has been disabled due to security or stability issues

### ISSUE THREAD

**Issue by myname1614** [itsecurityco/to-google-translate#91]
Firefox 74

![image](https://user-images.githubusercontent.com/34938365/75780590-5442d400-5d64-11ea-995c-c1e825efdc12.png)

more link to open page:
https://blocked.cdn.mozilla.net/ae0ffe5f-a7a2-48ec-9b01-2c0c9d3eb2e8.html

**Comment by itsecurityco** [comment]
Hello, 

That is not my extension. This is "To Google Translate" and you can installed here: https://addons.mozilla.org/en-US/firefox/addon/to-google-translate/

Cheers

**Comment by myname1614** [comment]
sorry )
